MyCRMNoSQL.Web/Models/MyCRM/Address.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
using MyCRMNoSQL.CustomExtensions;

namespace MyCRMNoSQL.Models
{
    public class Address
    {
        [Key]
        public string AddressId { get; set; }

        [MinLength(6, ErrorMessage = "must be valid")]
        [Display(Name = "Street")]
        public string Street { get; set; } = "None";

        [Display(Name = "Apt/Suite")]
        public string AptSuite { get; set; } = "None";

        [Required(ErrorMessage = "is required")]
        public string City { get; set; }

        [Required(ErrorMessage = "State is required")]
        public string State { get; set; }

        [Required(ErrorMessage = "is required")]
        [RegularExpression("^[0-9]{5}?$", ErrorMessage = "must be valid")]
        [Display(Name = "Zipcode")]
        public int ZipCode { get; set; }

        [Required]
        public string BusinessId { get; set; }

        public DateTime CreatedDate { get; set; } = DateTime.Now;

        public DateTime UpdatedDate { get; set; } = DateTime.Now;

        public static Address DbPrep(Address a)
        {
            a.Street = a.Street.Trim();
            a.AptSuite = a.AptSuite.Trim();
            a.City = MyExtensions.StringToUpper(a.City);
            a.State = a.State.Trim().ToUpper();

            return a;
        }

    }
}

MyCRMNoSQL.Web/Controllers/AddressController.cs
using Microsoft.AspNetCore.Mvc;
using MyCRMNoSQL.Core;
using MyCRMNoSQL.Models;
using MyCRMNoSQL.Service.Interfaces;

namespace MyCRMNoSQL.Web.Controllers
{
    public class AddressController : Controller
    {
        private readonly ILogger<AddressController> _logger;
        private readonly IExtension _extension;
        private readonly IAddressService _addressService;

        public AddressController(ILogger<AddressController> logger, IExtension extension, IAddressService addressService)
        {
            _logger = logger;
            _extension = extension;
            _addressService = addressService;
        }

        public IActionResult Get(string id)
        {
            if (!_extension.LoggedIn())
            {
                return RedirectToAction("Login", "User");
            }

            Address address = _addressService.Get(id);

            return View(address);
        }

        [HttpPost]
        public IActionResult Add(string id, AddressFormModel Address)
        {
            Address.BusinessId = id;

            if (!ModelState.IsValid)
            {
                return RedirectToAction("ViewOne", "CRM", new { id = id });
            }

            Address = AddressFormModel.DbPrep(Address);

            Address address = new()
            {
                Street = Address.Street,
                AptSuite = Address.AptSuite,
                City = Address.City,
                State = Address.State,
                ZipCode = Address.ZipCode,
                BuisinessId = Address.BusinessId,
                CreatedDate = Address.CreatedDate,
                UpdatedDate = Address.UpdatedDate
            };

            string Id = _addressService.Create(address);

            return RedirectToAction("ViewOne", "CRM", new { id = id });
        }

        [HttpPost]
        public IActionResult Update(string id, string Bid, AddressFormModel Address)
        {
            Address.BusinessId = Bid;

            if (!ModelState.IsValid)
            {
                return RedirectToAction("ViewOne", "CRM", new { id = Bid });
            }

            Address = AddressFormModel.DbPrep(Address);

            Address address = new()
            {
                Id = id,
                Street = Address.Street,
                AptSuite = Address.AptSuite,
                City = Address.City,
                State = Address.State,
                ZipCode = Address.ZipCode,
                BuisinessId = Address.BusinessId,
                UpdatedDate = Address.UpdatedDate
            };

            string Id = _addressService.Update(address);

            return RedirectToAction("ViewOne", "CRM", new { id = Bid });
        }

        public IActionResult Delete(string id, string Bid)
        {
            if (!_extension.LoggedIn())
            {
                return RedirectToAction("Login", "User");
            }

            bool Success = _addressService.Delete(id);

            if (!Success)
            {
                return Content("Delete did not work");
            }

            return RedirectToAction("ViewOne", "CRM", new { id = Bid });
        }
    }
}

MyCRMNoSQL.Web/Controllers/CRMController.cs
using Microsoft.AspNetCore.Mvc;
using MyCRMNoSQL.Models;
using MyCRMNoSQL.Core;
using MyCRMNoSQL.Service.Interfaces;
#pragma warning disable CS8601

namespace MyCRMNoSQL.Web.Controllers
{
    public class CRMController : Controller
    {
        private readonly ILogger<CRMController> _logger;
        private readonly IExtension _extension;
        private readonly IBusinessService _businessService;
        private readonly IAddressService _addressService;
        private readonly IStaffService _staffService;
        private readonly INoteService _noteService;
        private readonly IUpcomingTaskService _upcomingTask;
        private readonly IPurchaseService _purchaseService;
        private readonly IClientActivityService _clientActivityService;


        public CRMController(
            ILogger<CRMController> logger,
            IExtension extension,
            IBusinessService businessService,
            IAddressService addressService,
            IStaffService staffService,
            INoteService noteService,
            IUpcomingTaskService upcomingTaskService,
            IPurchaseService purchaseService,
            IClientActivityService clientActivityService)
        {
            _logger = logger;
            _extension = extension;
            _businessService = businessService;
            _addressService = addressService;
            _staffService = staffService;
            _noteService = noteService;
            _upcomingTask = upcomingTaskService;
            _purchaseService = purchaseService;
            _clientActivityService = clientActivityService;
        }

        public IActionResult Dashboard()
        {
            if(!_extension.LoggedIn())
            {
                return RedirectToAction("Login", "User");
            }

            List<Business> businessList = _businessService.GetAllWithLatestActivity();

            return View("Dashboard", businessList);
        }

        public IActionResult New()
        {
            if (!_extension.LoggedIn())
            {
                return RedirectToAction("Login", "User");
            }

            return View("NewBusiness");
        }

        public IActionResult NewClient(NewBusinessFormModel newBiz)
        {
            if (!ModelState.IsValid)
            {
                return New();
            }

            newBiz = NewBusinessFormModel.DbPrep(newBiz);

            bool Check = _businessService.CheckByName(newBiz.Name);

            if (Check == false)
            {
                ModelState.AddModelError("Name", "already exists");
                return New();
            }

            Business business = new()
            {
                Name = newBiz.Name,
                Industry = newBiz.Industry,
                Website = newBiz.Website,
                StartDate = newBiz.StartDate,
                UserId = _extension.UserId(),
                CreatedDate = newBiz.CreatedDate,
                UpdatedDate = newBiz.UpdatedDate
            };

            Address address = new()
            {
                Street = newBiz.Street,
                AptSuite = newBiz.AptSuite,
                City = newBiz.City,
                State = newBiz.State,
                CreatedDate = newBiz.CreatedDate,
                UpdatedDate = newBiz.UpdatedDate
            };

            Staff staff = new()
            {
                Position = newBiz.Position,
                FirstName = newBiz.FirstName,
                LastName = newBiz.LastName,
                PhoneNumber = newBiz.PhoneNumber,
                Email = newBiz.Email,
                CreatedDate = newBiz.CreatedDate,
                UpdatedDate = newBiz.UpdatedDate
            };

            string Id = _businessService.CreateClient(business, address, staff);

            return Dashboard();
        }

        public IActionResult ViewOne(string id)
        {
            if (!_extension.LoggedIn())
            {
                return RedirectToAction("Login", "User");
            }

            Business business = _businessService.Get(id);

            return View(business);
        }

        [HttpPost]
        public IActionResult Update(string id, BusinessFormModel businessForm)
        {
            businessForm = BusinessFormModel.DbPrep(businessForm);

            Business business = new()
            {
                Id = id,
                Name = businessForm.Name,
                Industry = businessForm.Industry,
                Website = businessForm.Website,
                PocId = businessForm.PocId,
                UpdatedDate = businessForm.UpdatedDate
            }; 

            string Id = _businessService.Update(business);

            return RedirectToAction("ViewOne", new { id = Id });
        }

        public IActionResult Delete(string id)
        {
            bool Success = _businessService.Delete(id);

            if (!Success)
            {
                return Content("Something went wrong...");
            }

            return Dashboard();
        }
    }
}

MyCRMNoSQL.Web/Controllers/StaffController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyCRMNoSQL.Models;
using MyCRMNoSQL.Core;
using MyCRMNoSQL.CustomExtensions;
using RethinkDb.Driver;
using System.Diagnostics.Contracts;
using System.Security.Cryptography;
using MyCRMNoSQL.Service.Interfaces;

namespace MyCRMNoSQL.Web.Controllers
{
    public class StaffController : Controller
    {
        private readonly ILogger<StaffController> _logger;
        private readonly IExtension _extension;
        private readonly IStaffService _staffService;

        public StaffController(ILogger<StaffController> logger, IExtension extension, IStaffService staffService)
        {
            _logger = logger;
            _extension = extension;
            _staffService = staffService;
        }

        public IActionResult Get(string id)
        {
            if (!_extension.LoggedIn())
            {
                return RedirectToAction("Login", "User");
            }

            Staff staff = _staffService.Get(id);

            return View(staff);
        }

        public IActionResult GetAll()
        {
            if (!_extension.LoggedIn())
            {
                return RedirectToAction("Login", "User");
            }

            List<Staff> staffList = _staffService.GetAll();

            return View(staffList);
        }

        [HttpPost]
        public IActionResult Add(string id, StaffFormModel Staff)
        {
            Staff.BusinessId = id;

            if (!ModelState.IsValid)
            {
                return RedirectToAction("ViewOne", "CRM", new { id = id });
            }

            Staff = StaffFormModel.DbPrep(Staff);

            Staff staff = new()
            {
                Position = Staff.Position,
                FirstName = Staff.FirstName,
                LastName = Staff.LastName,
                PhoneNumber = Staff.PhoneNumber,
                Email = Staff.Email,
                BusinessId = Staff.BusinessId,
                CreatedDate = Staff.CreatedDate,
                UpdatedDate = Staff.UpdatedDate
            };

            string Id = _staffService.Create(staff);

            return RedirectToAction("ViewOne", "CRM", new { id = id });
        }

        [HttpPost]
        public IActionResult Update(string id, string Bid, StaffFormModel Staff)
        {
            Staff.BusinessId = Bid;

            if (!ModelState.IsValid)
            {
                return RedirectToAction("ViewOne", "CRM", new { id = Bid });
            }

            Staff = StaffFormModel.DbPrep(Staff);

            Staff staff = new()
            {
                Id = id,
                Position = Staff.Position,
                FirstName = Staff.FirstName,
                LastName = Staff.LastName,
                PhoneNumber = Staff.PhoneNumber,
                Email = Staff.Email,
                BusinessId = Staff.BusinessId,
                UpdatedDate = Staff.UpdatedDate
            };

            string Id = _staffService.Update(staff);

            return RedirectToAction("ViewOne", "CRM", new { id = Bid });
        }

        public IActionResult Delete(string id, string Bid)
        {
            if (!_extension.LoggedIn())
            {
                return RedirectToAction("Login", "User");
            }

            bool Success = _staffService.Delete(id);

            if(!Success)
            {
                return Content("Something went wrong...");
            }

            return RedirectToAction("ViewOne", "CRM", new { id = Bid });
        }
    }
}

MyCRMNoSQL.Web/Controllers/UpcomingTaskController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyCRMNoSQL.Models;
using MyCRMNoSQL.Core;
using MyCRMNoSQL.CustomExtensions;
using RethinkDb.Driver;
using System.Diagnostics.Contracts;
using System.Security.Cryptography;
using MyCRMNoSQL.Service.Interfaces;

namespace MyCRMNoSQL.Web.Controllers
{
    public class UpcomingTaskController : Controller
    {
        private readonly ILogger<UpcomingTaskController> _logger;
        private readonly IExtension _extension;
        private readonly IUpcomingTaskService _upcomingTaskService;

        public UpcomingTaskController(ILogger<UpcomingTaskController> logger, IExtension extension, IUpcomingTaskService upcomingTaskService)
        {
            _logger = logger;
            _extension = extension;
            _upcomingTaskService = upcomingTaskService;
        }

        public IActionResult Get(string id)
        {
            if (!_extension.LoggedIn())
            {
                return RedirectToAction("Login", "User");
            }

            UpcomingTask task = _upcomingTaskService.Get(id);

            return View(task);
        }

        public IActionResult GetAll()
        {
            if (!_extension.LoggedIn())
            {
                return RedirectToAction("Login", "User");
            }

            List<UpcomingTask> taskList = _upcomingTaskService.GetAll();

            return View(taskList);
        }

        [HttpPost]
        public IActionResult Add(string id, UpcomingTaskFormModel Task)
        {
            Task.UserId = _extension.UserId();
            Task.BusinessId = id;

            if (!ModelState.IsValid)
            {
                return RedirectToAction("ViewOne", "CRM", new { id = id });
            }

            Task = UpcomingTaskFormModel.DbPrep(Task);

            UpcomingTask task = new()
            {
                UserId = Task.UserId,
                BusinessId = Task.BusinessId,
                StaffId = Task.StaffId,
                Type = Task.Type,
                Details = Task.Details,
                DueDate = Task.DueDate,
                Status = Task.Status,
                CreatedDate = Task.CreatedDate,
                UpdatedDate = Task.UpdatedDate,
            };

            string Id = _upcomingTaskService.Create(task);

            return RedirectToAction("ViewOne", "CRM", new { id = id });
        }

        [HttpPost]
        public IActionResult Update(string id, string Bid, UpcomingTaskFormModel Task)
        {
            Task.UserId = _extension.UserId();
            Task.BusinessId = Bid;

            if (!ModelState.IsValid)
            {
                return RedirectToAction("ViewOne", "CRM", new { id = Bid });
            }

            Task = UpcomingTaskFormModel.DbPrep(Task);

            UpcomingTask task = new()
            {
                Id = id,
                UserId = Task.UserId,
                BusinessId = Task.BusinessId,
                StaffId = Task.StaffId,
                Type = Task.Type,
                Details = Task.Details,
                DueDate = Task.DueDate,
                Status = Task.Status,
                UpdatedDate = Task.UpdatedDate
            };

            string Id = _upcomingTaskService.Update(task);

            return RedirectToAction("ViewOne", "CRM", new { id = id });
        }

        public IActionResult Delete(string id, string Bid)
        {
            if(!_extension.LoggedIn())
            {
                return RedirectToAction("Login", "User");
            }

            bool Success = _upcomingTaskService.Delete(id);

            if(!Success)
            {
                return Content("Something went wrong");
            }

            return RedirectToAction("ViewOne", "CRM", new { id = Bid });
        }
    }
}

MyCRMNoSQL.Web/Views/CRM/ViewOne.cshtml
@*@{
    ViewData["Title"] = ViewBag.Business.Name;
}

<div class="header">
    <div>
        <h1>@ViewBag.Business.Name</h1>
        <partial name="_Name"/>
    </div>
    <div>
        <a asp-controller="CRM" asp-action="Presentation" asp-route-businessId="@ViewBag.Business.BusinessId" class="btn btn-success">Presentation</a>
    </div>
</div>
<div>
    <div>
        <div>
            <div>
                <h1>Point of Contact</h1>
                <partial name="_POC"/>
            </div>
            <div>
                <div>
                    <h2>@ViewBag.Business.PointOfContact.Position: @ViewBag.Business.PointOfContact.FirstName @ViewBag.Business.PointOfContact.LastName</h2>
                </div>
                <div>
                    <h3>Phone: <a href="tel:@ViewBag.Business.PointOfContact.PhoneNumber">@ViewBag.Business.PointOfContact.PhoneNumber.ToString("(###) ###-####")</a></h3>
                </div>
                <div>
                    <h3>Email: <a href="mailto:@ViewBag.Business.PointOfContact.Email">@ViewBag.Business.PointOfContact.Email</a></h3>
                </div>
            </div>
            <div>
                <div>
                    <button class="btn btn-outline-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseStaff" aria-expanded="false" aria-controls="collapseStaff">Staff</button>
                    <button class="btn btn-link" data-bs-toggle="modal" data-bs-target="#StaffModal">Add</button>
                    <div class="modal fade" id="StaffModal" tabindex="-1" aria-labelledby="StaffModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h3>Add a New Staff Member</h3>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <partial name="_Staff"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="collapse" id="collapseStaff">
                    <div class="card card-body">
                        <div>
                            @foreach (StaffFormModel s in ViewBag.Business.StaffList)
                            {
                                <div>
                                    <p>@s.Position</p>
                                    <p>@s.FirstName @s.LastName</p>
                                    <p><a href="tel:@s.PhoneNumber">@s.PhoneNumber.ToString("(###) ###-####")</a></p>
                                    <p><a href="mailto:@s.Email">@s.Email</a></p>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <h3>
                    Business Website:
                    @if (ViewBag.Business.Website == "None")
                    {
                        <span id="W">
                            None Yet
                        </span>
                    }
                    else
                    {
                        <span>
                            <a href="@ViewBag.Business.Website" target="_blank">@ViewBag.Business.Website</a>
                        </span>
                    }
                </h3>
                <partial name="_Website"/>
            </div>
            <div>
                <h2>Founded in: @ViewBag.Business.StartDate.ToString("MMMM d, yyyy")</h2>
                <partial name="_UpdateSD"/>
            </div>
            <div>
                <h2>Industry: @ViewBag.Business.Industry</h2>
                <partial name="_Industry"/>
            </div>
            <div>
                <div>
                    <div>
                        <h1>Locations</h1>
                        <button class="btn btn-link" data-bs-toggle="modal" data-bs-target="#LocationModal">Add</button>
                    </div>
                    <div class="modal fade" id="LocationModal" tabindex="-1" aria-labelledby="LocationModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h3>Add a New Location</h3>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <partial name="_Address"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div>
                        @foreach (Address a in ViewBag.Business.AddressList)
                        {
                            <div>
                                <div>
                                    <div>
                                        <img src="~/images/Activity/Location.png" alt="ai">
                                    </div>
                                    <div>
                                        <h4>@a.Street</h4>
                                        <h4>@a.City, @a.State @a.ZipCode</h4>
                                    </div>
                                </div>
                                <a asp-controller="Address" asp-action="Delete" asp-route-businessId="@ViewBag.Business.BusinessId" asp-route-addressId="@a.AddressId">delete</a>
                            </div>
                        }
                    </div>
                </div>
                <div>
                    <div>
                        <h1>Notes</h1>
                        <button class="btn btn-link" data-bs-toggle="modal" data-bs-target="#NoteModal">Add</button>
                    </div>
                    <div>
                        <div>
                            @foreach (NoteFormModel n in ViewBag.Business.NoteList)
                            {
                                <div>
                                    <div>
                                        <img src="~/images/Activity/Note.png" alt="ai">
                                    </div>
                                    <div>
                                        <h5>@n.Details</h5>
                                        <p>@n.CreatedDate.ToString("M/d @ h:mm tt")</p>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
                <div class="modal fade" id="NoteModal" tabindex="-1" aria-labelledby="NoteModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h3>Add a Note</h3>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <partial name="_Note"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <p>
                    <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapsePurchases" aria-expanded="false" aria-controls="collapsePurchases">
                        Purchases (@ViewBag.Business.PurchaseList.Count)
                    </button>
                </p>
                <div>
                    <div class="collapse" id="collapsePurchases">
                        <div class="card card-body">
                            @if (ViewBag.Business.PurchaseList.Count > 0)
                            {
                                @foreach (PurchaseFormModel p in ViewBag.Business.PurchaseList)
                                {
                                    <div>
                                        <div>
                                            <img src="~/images/Activity/Purchase.png" alt="ai">
                                        </div>
                                        <div>
                                            <p>@p.Product.Name at</p>
                                            <p>@p.Address.City, @p.Address.State</p>
                                        </div>
                                    </div>
                                }
                            }
                            else
                            {
                                <p>No purchases yet</p>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="accordion accordion-flush task" id="accordionFlushTask">
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTask" aria-expanded="false" aria-controls="flush-collapseTask">
                        Up Coming Tasks (@ViewBag.Business.TaskList.Count)
                    </button>
                </h2>
                <div id="flush-collapseTask" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushTask">
                    <div class="accordion-body">
                        <button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#TaskModalT">Add</button>
                        @foreach (UpcomingTaskFormModel t in ViewBag.Business.TaskList)
                        {
                            @if (t.DueDate >= DateTime.Now)
                            {
                                <div>
                                    @if (t.Type == "Phone Call")
                                    {
                                        <div>
                                            <img src="~/images/Activity/PhoneCall.svg" alt="ai">
                                        </div>
                                    }
                                    @if (t.Type == "Email")
                                    {
                                        <div class="img">
                                            <img src="~/images/Activity/Email.svg" alt="ai">
                                        </div>
                                    }
                                    @if (t.Type == "Presentation")
                                    {
                                        <div class="img">
                                            <img src="~/images/Activity/Presentation.png" alt="ai">
                                        </div>
                                    }
                                    <div>
                                        <p>with @t.Staff.FirstName</p>
                                        <p>@t.DueDate.ToString("MM/d @ h:mm tt")</p>
                                        <p>@t.Details</p>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="TaskModalT" tabindex="-1" aria-labelledby="TaskModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 id="TaskModalLabel">Add a Task</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <partial name="_Task"/>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <partial name="_BusinessActivity"/>
        </div>
    </div>
</div>
*@

MyCRMNoSQL.Web/Views/CRM/_Name.cshtml
@*@model Business

<form asp-controller="CRM" asp-action="Update" asp-route-businessId="@ViewBag.Business.BusinessId" method="POST">
    <input asp-for="Name" class="form-control" value="@ViewBag.Business.Name">
    <button type="submit" class="btn btn-link">Update</button>
</form>*@

MyCRMNoSQL.Web/Views/CRM/_Staff.cshtml
@*@model StaffFormModel

<form asp-controller="Staff" asp-action="Add" asp-route-businessId="@ViewBag.Business.BusinessId" method="POST">
    <div class="row">
        <div class="col-4">
            <label asp-for="Position" class="form-label"></label>
            <span asp-validation-for="Position"></span>
            <select asp-for="Position" class="form-control">
                <option value="None" selected disabled hidden>Select</option>
                <option value="Owner">Owner</option>
                <option value="Gate Keeper">Gate Keeper</option>
                <option value="Marketing">Marketing</option>
                <option value="Other">Other</option>
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <label asp-for="FirstName" class="form-label"></label>
            <span asp-validation-for="FirstName"></span>
            <input asp-for="FirstName" class="form-control">
        </div>
        <div class="col-6">
            <label asp-for="LastName" class="form-label"></label>
            <span asp-validation-for="LastName"></span>
            <input asp-for="LastName" class="form-control">
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <label asp-for="PhoneNumber" class="form-label"></label>
            <span asp-validation-for="PhoneNumber"></span>
            <input asp-for="PhoneNumber" class="form-control">
        </div>
        <div class="col-6">
            <label asp-for="Email" class="form-label"></label>
            <span asp-validation-for="Email"></span>
            <input asp-for="Email" class="form-control">
        </div>
    </div>
    <br>
    <button type="submit" class="btn btn-outline-success">Add Staff</button>
</form>*@